version: '3.9'

services:
  # Spring Boot application..
  spring-boot-app:
    image: task-be
    ports:
      - "8090:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres  # Use container port 5432
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW-SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  # PostgreSQL database
  db:
    image: postgres
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s